### ISSUE TITLE
Zodiac Exit Module - Task List

### ISSUE THREAD

**Issue by carlosfebres** [gnosis/zodiac-module-exit#53]
### Summary
In order to consider the Exit Module & Exit app fully done the following tasks have to be completed:
- Exit App
    - [ ] Add missing networks to the network switcher
- Zodiac
    -  [ ] Add the master copies of the Exit Module (ERC21 & ERC721 versions) for every network to deploy proxies 
    -  [ ] Update app to determine which version of the exit module will used
-  DevOps
    - Deploy Exit App (preferably a continues deployment integration)
    - Deploy the `ExitERC20Module` & `ExitERC721Module` contracts on the following networks:
        - [ ] Mainnet
        - [ ] Rinkeby
        - [ ] Goerli
        - [ ] Gnosis Chain
        - [ ] Polygon
        - [ ] Binance Smart Chain
        - [ ] Energy Web Chain
        - [ ] Arbitrum
        - [ ] Aurora
        - [ ] Avalanche
        - [ ] Optimism
        - [ ] Volta

**Comment by samepant** [comment]
I can talk to gnosis devops about getting a deployment going. This app can be hosted on ipfs right?

**Comment by carlosfebres** [comment]
Thanks @samepant, yes it can be hosted in IPFS 👍🏻

**Comment by samepant** [comment]
I've got Fleek setup and ready for whenever the exit-app PR is merged, will auto deploy merges into Master.

**Comment by samepant** [comment]
Hey @carlosfebres what do you think about merging in the Exit app branch so we can get a deployment of the app up? Is there anything else missing that we need before deploying?

**Comment by carlosfebres** [comment]
> Hey @carlosfebres what do you think about merging in the Exit app branch so we can get a deployment of the app up? Is there anything else missing that we need before deploying?

Hi @samepant! Sure, let me check with tests are failing and we can merge afterwards

**Comment by carlosfebres** [comment]
@samepant I just merge the Exit App PR 🚀
